services:
  pg:
    image: bitnami/postgresql:17.6.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: processing
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - pg_data:/bitnami/postgresql

volumes:
  pg_data: